name: Docker Image CI
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_IMAGE: sub-convert

    steps:
    - name: Check out repository
      uses: actions/checkout@v4  # 更新到稳定版本

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # 更新到最新版

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64  # 移除非主流armv7架构
        push: true
        tags: |
          ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        
    - name: Update Docker Hub description
      run: |
        # 使用内置变量获取仓库信息
        DESCRIPTION="修改自肥羊的订阅转换项目 | 项目仓库: https://github.com/${{ github.repository }}"
        REPO_NAME="${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}"
        
        # 调用 Docker Hub API 更新描述
        curl -X PATCH \
          -H "Authorization: Bearer $DOCKER_TOKEN" \  # 使用环境变量
          -H "Content-Type: application/json" \
          -d "{\"full_description\": \"$DESCRIPTION\"}" \
          "https://hub.docker.com/v2/repositories/$REPO_NAME/"
